import {
  Activity,
  CheckCircle2,
  CircleDollarSign,
  Clock3,
  Download,
  PackageCheck,
  RefreshCcw,
  ShoppingBag,
} from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import {
  OrderStatusChart,
  SalesTrendChart,
  TopProductsChart,
} from '../components/BusinessCharts'
import { apiService, getErrorMessage } from '../services/api'
import type {
  BusinessKpis,
  OrderStatusMetric,
  SalesTrendPoint,
  TopMerchantMetric,
  TopProductMetric,
} from '../types/api'
import { wholeMoney as money } from '../utils/format'

const decimal = new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 })
const rangeOptions = [30, 90, 365] as const

interface AnalyticsData {
  kpis: BusinessKpis
  trend: SalesTrendPoint[]
  statuses: OrderStatusMetric[]
  products: TopProductMetric[]
  merchants: TopMerchantMetric[]
}

function csvCell(value: string | number) {
  let text = String(value)
  if (typeof value === 'string' && /^[=+\-@]/.test(value)) text = `'${text}`
  return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text
}

function downloadAnalyticsCsv(data: AnalyticsData, days: number) {
  const rows: Array<Array<string | number>> = [
    ['Wholesale Hub analytics report'],
    ['Sales trend period', `Last ${days} days`],
    ['Other metrics', 'All time'],
    ['Generated', new Date().toISOString()],
    [],
    ['BUSINESS KPIS'],
    ['Metric', 'Value'],
    ['Total orders', data.kpis.totalOrders],
    ['Open orders', data.kpis.openOrders],
    ['Completed orders', data.kpis.completedOrders],
    ['Cancelled orders', data.kpis.cancelledOrders],
    ['Total sales', data.kpis.totalSales],
    ['Units sold', data.kpis.unitsSold],
    ['Average order value', data.kpis.averageOrderValue],
    ['Completion rate', `${data.kpis.completionRate}%`],
    ['Cancellation rate', `${data.kpis.cancellationRate}%`],
    [],
    ['SALES TREND'],
    ['Date', 'Orders', 'Units', 'Sales'],
    ...data.trend.map((item) => [item.date, item.orderCount, item.unitsSold, item.totalSales]),
    [],
    ['TOP PRODUCTS'],
    ['Product', 'Merchant', 'Orders', 'Units', 'Sales'],
    ...data.products.map((item) => [
      item.productName,
      item.merchantName,
      item.orderCount,
      item.unitsSold,
      item.totalSales,
    ]),
    [],
    ['TOP MERCHANTS'],
    ['Merchant', 'Catalog products', 'Orders', 'Units', 'Sales'],
    ...data.merchants.map((item) => [
      item.merchantName,
      item.catalogProductCount,
      item.orderCount,
      item.unitsSold,
      item.totalSales,
    ]),
  ]
  const blob = new Blob([rows.map((row) => row.map(csvCell).join(',')).join('\n')], {
    type: 'text/csv;charset=utf-8',
  })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `wholesale-analytics-${new Date().toISOString().slice(0, 10)}.csv`
  link.click()
  URL.revokeObjectURL(url)
}

export function AnalyticsPage() {
  const [days, setDays] = useState<(typeof rangeOptions)[number]>(90)
  const [data, setData] = useState<AnalyticsData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [updatedAt, setUpdatedAt] = useState<Date | null>(null)

  const loadAnalytics = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const [kpis, trend, statuses, products, merchants] = await Promise.all([
        apiService.getBusinessKpis(),
        apiService.getSalesTrend(days),
        apiService.getOrderStatusReport(),
        apiService.getTopProductsReport(10),
        apiService.getTopMerchantsReport(10),
      ])
      setData({ kpis, trend, statuses, products, merchants })
      setUpdatedAt(new Date())
    } catch (requestError) {
      setError(getErrorMessage(requestError))
    } finally {
      setLoading(false)
    }
  }, [days])

  useEffect(() => {
    void loadAnalytics()
  }, [loadAnalytics])

  const businessInsights = useMemo(() => {
    if (!data) return []
    const revenuePerUnit = data.kpis.unitsSold === 0 ? 0 : data.kpis.totalSales / data.kpis.unitsSold
    const completedRevenueShare = data.kpis.totalSales === 0
      ? 0
      : (data.kpis.completedSales / data.kpis.totalSales) * 100
    const bestProduct = data.products[0]
    return [
      {
        label: 'Revenue per unit',
        value: money.format(revenuePerUnit),
        detail: 'Average revenue generated by each sold unit',
      },
      {
        label: 'Completed revenue',
        value: `${decimal.format(completedRevenueShare)}%`,
        detail: `${money.format(data.kpis.completedSales)} from completed orders`,
      },
      {
        label: 'Best-selling product',
        value: bestProduct?.productName ?? 'No sales yet',
        detail: bestProduct ? `${bestProduct.unitsSold.toLocaleString()} units sold` : 'Create an order to build rankings',
      },
    ]
  }, [data])

  if (loading && !data) {
    return (
      <div className="dashboard-loading" aria-label="Loading analytics">
        <div className="skeleton-row">
          {[1, 2, 3, 4].map((item) => <div className="skeleton skeleton-card" key={item} />)}
        </div>
        <div className="skeleton skeleton-large" />
      </div>
    )
  }

  if (!data) {
    return (
      <section className="error-state">
        <Activity size={42} aria-hidden="true" />
        <h2>Analytics unavailable</h2>
        <p>{error || 'The reporting service did not return any data.'}</p>
        <button className="button primary" type="button" onClick={() => void loadAnalytics()}>
          Try again
        </button>
      </section>
    )
  }

  const cards = [
    { label: 'Total sales', value: money.format(data.kpis.totalSales), detail: 'All non-cancelled orders', icon: CircleDollarSign },
    { label: 'Total orders', value: data.kpis.totalOrders.toLocaleString(), detail: `${data.kpis.openOrders} currently open`, icon: ShoppingBag },
    { label: 'Units sold', value: data.kpis.unitsSold.toLocaleString(), detail: `${decimal.format(data.kpis.averageUnitsPerOrder)} per order`, icon: PackageCheck },
    { label: 'Average order', value: money.format(data.kpis.averageOrderValue), detail: 'Revenue per order', icon: Activity },
    { label: 'Completion rate', value: `${decimal.format(data.kpis.completionRate)}%`, detail: `${data.kpis.completedOrders} completed`, icon: CheckCircle2 },
    { label: 'Open orders', value: data.kpis.openOrders.toLocaleString(), detail: `${data.kpis.cancelledOrders} cancelled`, icon: Clock3 },
  ]

  return (
    <section className="analytics-page">
      <div className="page-intro analytics-intro">
        <div>
          <span className="eyebrow">Decision support</span>
          <h2>Business analytics</h2>
          <p>Monitor revenue, order execution, product demand, and merchant performance.</p>
        </div>
        <div className="page-actions">
          <button className="button secondary" type="button" onClick={() => downloadAnalyticsCsv(data, days)}>
            <Download size={16} aria-hidden="true" />
            Export report
          </button>
          <button className="button secondary" type="button" onClick={() => void loadAnalytics()} disabled={loading}>
            <RefreshCcw size={16} aria-hidden="true" className={loading ? 'spin' : ''} />
            {loading ? 'Refreshing…' : 'Refresh'}
          </button>
        </div>
      </div>

      {error ? <div className="alert error" role="alert">{error}</div> : null}
      <div className="analytics-meta">
        <span>Live database metrics</span>
        <span>{updatedAt ? `Updated ${updatedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : ''}</span>
      </div>

      <section className="analytics-kpi-grid" aria-label="Key performance indicators">
        {cards.map(({ label, value, detail, icon: Icon }) => (
          <article className="analytics-kpi" key={label}>
            <span className="analytics-kpi-icon"><Icon size={20} aria-hidden="true" /></span>
            <span>{label}</span>
            <strong>{value}</strong>
            <small>{detail}</small>
          </article>
        ))}
      </section>

      <section className="panel chart-panel trend-panel" aria-labelledby="sales-trend-title">
        <header className="panel-header analytics-panel-header">
          <div>
            <h2 id="sales-trend-title">Sales trend</h2>
            <p>Daily revenue and order volume</p>
          </div>
          <div className="range-selector" aria-label="Sales trend date range">
            {rangeOptions.map((option) => (
              <button
                type="button"
                key={option}
                className={days === option ? 'active' : ''}
                aria-pressed={days === option}
                onClick={() => setDays(option)}
              >
                {option === 365 ? '1 year' : `${option} days`}
              </button>
            ))}
          </div>
        </header>
        <SalesTrendChart data={data.trend} />
      </section>

      <div className="analytics-chart-grid">
        <section className="panel chart-panel" aria-labelledby="order-status-title">
          <header className="panel-header">
            <div>
              <h2 id="order-status-title">Order status mix</h2>
              <p>Fulfillment pipeline distribution</p>
            </div>
          </header>
          <OrderStatusChart data={data.statuses} />
        </section>
        <section className="panel chart-panel" aria-labelledby="top-products-title">
          <header className="panel-header">
            <div>
              <h2 id="top-products-title">Top products</h2>
              <p>Highest revenue-generating catalog items</p>
            </div>
          </header>
          <TopProductsChart data={data.products} />
        </section>
      </div>

      <section className="insight-strip analytics-insights" aria-label="Calculated business insights">
        {businessInsights.map((insight) => (
          <article key={insight.label}>
            <span>{insight.label}</span>
            <strong title={insight.value}>{insight.value}</strong>
            <p>{insight.detail}</p>
          </article>
        ))}
      </section>

      <section className="panel" aria-labelledby="merchant-ranking-title">
        <header className="panel-header">
          <div>
            <h2 id="merchant-ranking-title">Merchant performance</h2>
            <p>Ranked by revenue generated through product sales</p>
          </div>
          <span className="panel-meta">Top {data.merchants.length}</span>
        </header>
        <div className="table-scroll">
          <table>
            <caption className="sr-only">Merchants ranked by total sales</caption>
            <thead>
              <tr><th>Rank</th><th>Merchant</th><th>Catalog</th><th>Orders</th><th>Units</th><th>Sales</th></tr>
            </thead>
            <tbody>
              {data.merchants.length === 0 ? (
                <tr><td className="empty-table" colSpan={6}>No merchant sales data is available.</td></tr>
              ) : data.merchants.map((merchant, index) => (
                <tr key={merchant.merchantId}>
                  <td><strong className="rank-number">#{index + 1}</strong></td>
                  <td><strong>{merchant.merchantName}</strong></td>
                  <td>{merchant.catalogProductCount.toLocaleString()} products</td>
                  <td>{merchant.orderCount.toLocaleString()}</td>
                  <td>{merchant.unitsSold.toLocaleString()}</td>
                  <td><strong>{money.format(merchant.totalSales)}</strong></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </section>
  )
}
